import { useEffect, useState } from 'react';
import PageHeader from '../components/PageHeader';
import Modal from '../components/Modal';
import Toast from '../components/Toast';
import { articlesApi, categoriesApi, partiesApi } from '../api/resources';
import { fileUrl, money } from '../utils/format';
import { usePermission } from '../context/PermissionContext';

export default function Articles() {
  const { canCreate, canEdit, canDelete } = usePermission();
  const [items, setItems] = useState([]); const [categories, setCategories] = useState([]); const [parties, setParties] = useState([]); const [modal, setModal] = useState(null); const [busy, setBusy] = useState(false); const [toast, setToast] = useState(null); const [form, setForm] = useState({ name: '', style_code: '', category_id: '', size: '', total_pieces: '', rate: '', party_id: '', description: '', images: [] });
  const load = async () => { try { const [a, c, p] = await Promise.all([articlesApi.list(), categoriesApi.list(), partiesApi.list()]); const ad = a.data?.data; const cd = c.data?.data; const pd = p.data?.data; setItems(ad?.articles ?? ad?.items ?? a.data?.articles ?? a.data?.items ?? []); setCategories(cd?.categories ?? cd?.items ?? c.data?.categories ?? c.data?.items ?? []); setParties(pd?.parties ?? pd?.items ?? p.data?.parties ?? p.data?.items ?? []); } catch (err) { setToast({ type: 'error', message: err.response?.data?.message || 'Unable to load articles.' }); } };
  useEffect(() => { load(); }, []);
  const save = async (event) => { event.preventDefault(); setBusy(true); try { const fd = new FormData(); ['name', 'style_code', 'category_id', 'size', 'total_pieces', 'rate', 'party_id', 'description'].forEach((key) => fd.append(key, form[key])); [...form.images].forEach((file) => fd.append('images', file)); if (modal.mode === 'create') await articlesApi.create(fd); else await articlesApi.update(modal.item.id, fd); setModal(null); setToast({ type: 'success', message: 'Article saved.' }); await load(); } catch (err) { setToast({ type: 'error', message: err.response?.data?.message || 'Unable to save article.' }); } finally { setBusy(false); } };
  const remove = async (item) => { if (!window.confirm(`Delete ${item.name || item.code || item.id}?`)) return; try { await articlesApi.remove(item.id); await load(); setToast({ type: 'success', message: 'Article deleted.' }); } catch (err) { setToast({ type: 'error', message: err.response?.data?.message || 'Delete failed.' }); } };
  const open = (mode, item = null) => setModal({ mode, item });
  return <div className="page"><Toast message={toast?.message} type={toast?.type} onClose={() => setToast(null)} /><PageHeader title="Articles / Styles" subtitle="Production items with quantities, rates, parties and images." actions={canCreate('articles') && <button className="primary-button" onClick={() => { setForm({ name: '', style_code: '', category_id: '', size: '', total_pieces: '', rate: '', party_id: '', description: '', images: [] }); open('create'); }}>+ Add Article</button>} /><div className="article-grid">{items.map((item) => <article className="article-card" key={item.id}><div className="article-image">{item.images?.[0] || item.image ? <img src={fileUrl(item.images?.[0] || item.image)} alt="" /> : <span>NO IMAGE</span>}</div><div className="article-body"><div className="eyebrow">{item.code || `#${item.id}`}</div><h3>{item.name}</h3><div className="muted-text">{item.category_name || item.category || 'No category'}</div><div className="article-metrics"><span>{item.total_pieces ?? 0} pcs</span><span>{money(item.rate)}</span></div><div className="row-actions">{canEdit('articles') && <button className="text-button" onClick={() => { setForm({ name: item.name || '', code: item.code || '', category_id: item.category_id || '', size: item.size || '', total_pieces: item.total_pieces || '', rate: item.rate || '', party_id: item.party_id || '', description: item.description || '', images: [] }); open('edit', item); }}>Edit</button>}{canDelete('articles') && <button className="danger-link" onClick={() => remove(item)}>Delete</button>}</div></div></article>)}</div>{!items.length && <div className="empty-state"><h2>No articles yet</h2><p>Create the first article/style to begin production tracking.</p></div>}
    {modal && <Modal title={modal.mode === 'create' ? 'Create Article / Style' : `Edit ${modal.item.name || 'Article'}`} onClose={() => setModal(null)} footer={<><button className="secondary-button" onClick={() => setModal(null)}>Cancel</button><button className="primary-button" form="article-form" disabled={busy}>{busy ? 'Saving…' : 'Save Article'}</button></>}><form id="article-form" className="form-grid" onSubmit={save}><label>Article name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Code<input value={form.style_code} onChange={(e) => setForm({ ...form, style_code: e.target.value })} /></label><label>Category<select value={form.category_id} onChange={(e) => setForm({ ...form, category_id: e.target.value })}><option value="">Select category</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Party<select value={form.party_id} onChange={(e) => setForm({ ...form, party_id: e.target.value })}><option value="">Select party</option>{parties.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Size<input value={form.size} onChange={(e) => setForm({ ...form, size: e.target.value })} /></label><label>Total pieces<input type="number" min="0" value={form.total_pieces} onChange={(e) => setForm({ ...form, total_pieces: e.target.value })} /></label><label>Per-piece rate<input type="number" min="0" step="0.01" value={form.rate} onChange={(e) => setForm({ ...form, rate: e.target.value })} /></label><label>Images<input type="file" accept="image/*" multiple onChange={(e) => setForm({ ...form, images: e.target.files ? Array.from(e.target.files) : [] })} /></label><label className="full">Description<textarea rows="4" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label></form></Modal>}
  </div>;
}
