import { useEffect, useState } from 'react';
import PageHeader from '../components/PageHeader';
import Modal from '../components/Modal';
import Toast from '../components/Toast';
import { billsApi, partiesApi, articlesApi } from '../api/resources';
import { money } from '../utils/format';
import { usePermission } from '../context/PermissionContext';

export default function Bills() {
  const { canCreate } = usePermission();
  const [items,setItems]=useState([]); const [parties,setParties]=useState([]); const [articles,setArticles]=useState([]); const [modal,setModal]=useState(false); const [toast,setToast]=useState(null); const [form,setForm]=useState({bill_number:'',party_id:'',bill_date:'',challan_id:'',article_id:'',quantity:'',rate:'',paid_amount:'',notes:''});
  const load=async()=>{try{const [b,p,a]=await Promise.all([billsApi.list(),partiesApi.list(),articlesApi.list()]);const bd=b.data?.data,pd=p.data?.data,ad=a.data?.data;setItems(bd?.items??[]);setParties(pd?.items??[]);setArticles(ad?.articles??ad?.items??[]);}catch(err){setToast({type:'error',message:err.response?.data?.message||'Unable to load bills.'});}};
  useEffect(()=>{load();},[]);
  const amount=Number(form.quantity||0)*Number(form.rate||0);
  const save=async(e)=>{e.preventDefault();try{await billsApi.create({bill_number:form.bill_number,party_id:Number(form.party_id),bill_date:form.bill_date,challan_id:form.challan_id?Number(form.challan_id):undefined,paid_amount:Number(form.paid_amount||0),notes:form.notes,items:[{article_id:Number(form.article_id),quantity:Number(form.quantity),rate:Number(form.rate||0)}]});setModal(false);await load();setToast({type:'success',message:'Bill created.'});}catch(err){setToast({type:'error',message:err.response?.data?.message||'Unable to create bill.'});}};
  return <div className="page"><Toast message={toast?.message} type={toast?.type} onClose={()=>setToast(null)}/><PageHeader title="Billing" subtitle="Party bills with quantity × rate calculation, challan reference and balances." actions={canCreate('billing')&&<button className="primary-button" onClick={()=>setModal(true)}>+ Create Bill</button>}/><div className="table-card"><div className="table-scroll"><table><thead><tr><th>Bill</th><th>Party</th><th>Date</th><th>Total</th><th>Paid</th><th>Previous</th><th>Status</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{item.bill_number}</td><td>{item.party_name||item.party_id}</td><td>{item.bill_date}</td><td>{money(item.total_amount)}</td><td>{money(item.paid_amount)}</td><td>{money(item.previous_balance)}</td><td><span className="status-badge">{item.status}</span></td></tr>)}{!items.length&&<tr><td colSpan="7"><div className="table-empty">No bills yet.</div></td></tr>}</tbody></table></div></div>{modal&&<Modal title="Create Bill" onClose={()=>setModal(false)} footer={<><button className="secondary-button" onClick={()=>setModal(false)}>Cancel</button><button className="primary-button" form="bill-form">Save Bill</button></>}><form id="bill-form" className="form-grid" onSubmit={save}><label>Bill number<input required value={form.bill_number} onChange={e=>setForm({...form,bill_number:e.target.value})}/></label><label>Bill date<input type="date" required value={form.bill_date} onChange={e=>setForm({...form,bill_date:e.target.value})}/></label><label>Party<select required value={form.party_id} onChange={e=>setForm({...form,party_id:e.target.value})}><option value="">Select party</option>{parties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Challan ID<input value={form.challan_id} onChange={e=>setForm({...form,challan_id:e.target.value})}/></label><label>Article<select required value={form.article_id} onChange={e=>setForm({...form,article_id:e.target.value})}><option value="">Select article</option>{articles.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Quantity<input type="number" min="1" required value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label>Rate<input type="number" min="0" step="0.01" required value={form.rate} onChange={e=>setForm({...form,rate:e.target.value})}/></label><label>Paid amount<input type="number" min="0" step="0.01" value={form.paid_amount} onChange={e=>setForm({...form,paid_amount:e.target.value})}/></label><label className="full">Notes<textarea rows="3" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="calculation-box full"><span>Calculated amount</span><strong>{money(amount)}</strong></div></form></Modal>}</div>;
}
