import { useEffect, useState } from 'react';
import PageHeader from '../components/PageHeader';
import Modal from '../components/Modal';
import Toast from '../components/Toast';
import { challansApi, partiesApi, articlesApi } from '../api/resources';
import { usePermission } from '../context/PermissionContext';

export default function Challans() {
  const { canCreate } = usePermission();
  const [items, setItems] = useState([]); const [parties, setParties] = useState([]); const [articles, setArticles] = useState([]); const [modal, setModal] = useState(false); const [toast, setToast] = useState(null);
  const [form, setForm] = useState({ challan_number: '', party_id: '', challan_date: '', article_id: '', quantity: '', rate: '', notes: '' });
  const load = async () => { try { const [c, p, a] = await Promise.all([challansApi.list(), partiesApi.list(), articlesApi.list()]); const cd=c.data?.data, pd=p.data?.data, ad=a.data?.data; setItems(cd?.items ?? []); setParties(pd?.items ?? []); setArticles(ad?.articles ?? ad?.items ?? []); } catch(err) { setToast({type:'error',message:err.response?.data?.message||'Unable to load challans.'}); } };
  useEffect(()=>{load();},[]);
  const save = async (e) => { e.preventDefault(); try { await challansApi.create({ challan_number: form.challan_number, party_id: Number(form.party_id), challan_date: form.challan_date, notes: form.notes, items: [{ article_id: Number(form.article_id), quantity: Number(form.quantity), rate: Number(form.rate || 0) }] }); setModal(false); await load(); setToast({type:'success',message:'Challan created.'}); } catch(err){ setToast({type:'error',message:err.response?.data?.message||'Unable to create challan.'}); } };
  return <div className="page"><Toast message={toast?.message} type={toast?.type} onClose={()=>setToast(null)}/><PageHeader title="Challans" subtitle="Dispatch records by party, article, quantity and date." actions={canCreate('challans')&&<button className="primary-button" onClick={()=>setModal(true)}>+ Create Challan</button>}/><div className="table-card"><div className="table-scroll"><table><thead><tr><th>Challan</th><th>Party</th><th>Date</th><th>Status</th><th>Notes</th></tr></thead><tbody>{items.map((item)=><tr key={item.id}><td>{item.challan_number}</td><td>{item.party_name||item.party_id}</td><td>{item.challan_date}</td><td><span className="status-badge">{item.status}</span></td><td>{item.notes||'—'}</td></tr>)}{!items.length&&<tr><td colSpan="5"><div className="table-empty">No challans yet.</div></td></tr>}</tbody></table></div></div>{modal&&<Modal title="Create Challan" onClose={()=>setModal(false)} footer={<><button className="secondary-button" onClick={()=>setModal(false)}>Cancel</button><button className="primary-button" form="challan-form">Save Challan</button></>}><form id="challan-form" className="form-grid" onSubmit={save}><label>Challan number<input required value={form.challan_number} onChange={e=>setForm({...form,challan_number:e.target.value})}/></label><label>Date<input type="date" required value={form.challan_date} onChange={e=>setForm({...form,challan_date:e.target.value})}/></label><label>Party<select required value={form.party_id} onChange={e=>setForm({...form,party_id:e.target.value})}><option value="">Select party</option>{parties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Article<select required value={form.article_id} onChange={e=>setForm({...form,article_id:e.target.value})}><option value="">Select article</option>{articles.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Quantity<input type="number" min="1" required value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label>Rate<input type="number" min="0" step="0.01" value={form.rate} onChange={e=>setForm({...form,rate:e.target.value})}/></label><label className="full">Notes<textarea rows="3" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></form></Modal>}</div>;
}
