import { useEffect, useMemo, useState } from 'react';
import PageHeader from '../components/PageHeader';
import Modal from '../components/Modal';
import Toast from '../components/Toast';
import { usersApi, rolesApi, metaApi } from '../api/resources';
import { PAGE_DEFINITIONS, ACTIONS, DEFAULT_PERMISSIONS } from '../utils/pages';
import { fileUrl } from '../utils/format';
import { usePermission } from '../context/PermissionContext';

function buildPermissions() { return structuredClone(DEFAULT_PERMISSIONS); }

export default function Users() {
  const { canCreate, canEdit, canDelete } = usePermission();
  const [users, setUsers] = useState([]); const [roles, setRoles] = useState([]); const [pages, setPages] = useState(PAGE_DEFINITIONS);
  const [search, setSearch] = useState(''); const [modal, setModal] = useState(null); const [busy, setBusy] = useState(false); const [toast, setToast] = useState(null);
  const empty = { username: '', password: '', role_id: '', profilePicture: null, is_active: true, is_permission: true, permissions: buildPermissions() };
  const [form, setForm] = useState(empty);

  const load = async () => {
    try {
      const [usersResponse, rolesResponse] = await Promise.all([usersApi.list(), rolesApi.list()]);
      const userData = usersResponse.data?.data; const roleData = rolesResponse.data?.data;
      setUsers(userData?.users ?? userData?.items ?? usersResponse.data?.users ?? usersResponse.data?.items ?? []);
      setRoles(roleData?.roles ?? roleData?.items ?? rolesResponse.data?.roles ?? rolesResponse.data?.items ?? []);
      try { const pageResponse = await metaApi.pages(); const remote = pageResponse.data?.data?.pages; if (Array.isArray(remote) && remote.length) setPages(remote.map((p) => ({ key: p.key || p.name || p, label: p.label || p.name || p }))); } catch { /* local page list remains available */ }
    } catch (err) { setToast({ type: 'error', message: err.response?.data?.message || 'Unable to load users.' }); }
  };
  useEffect(() => { load(); }, []);

  const filtered = useMemo(() => { const n = search.toLowerCase(); return users.filter((user) => `${user.username} ${user.role || ''}`.toLowerCase().includes(n)); }, [users, search]);
  const openCreate = () => { const next = { ...empty, permissions: buildPermissions(), role_id: roles[0]?.id ?? '' }; setForm(next); setModal({ mode: 'create' }); };
  const openEdit = (user) => { const permissions = buildPermissions(); Object.entries(user.permissions || {}).forEach(([page, values]) => { if (!permissions[page]) permissions[page] = { can_view: false, can_create: false, can_edit: false, can_delete: false }; permissions[page] = { can_view: Boolean(values.can_view), can_create: Boolean(values.can_create), can_edit: Boolean(values.can_edit), can_delete: Boolean(values.can_delete) }; }); setForm({ ...empty, username: user.username || '', role_id: user.roleId || roles.find((r) => r.name === user.roleName || r.name === user.role)?.id || '', is_active: user.is_active !== false, is_permission: user.is_permission !== false, permissions }); setModal({ mode: 'edit', user }); };
  const setAll = (action, checked) => { setForm((current) => ({ ...current, permissions: Object.fromEntries(Object.entries(current.permissions).map(([page, value]) => [page, { ...value, [`can_${action}`]: checked }])) })); };
  const togglePermission = (page, action) => setForm((current) => ({ ...current, permissions: { ...current.permissions, [page]: { ...current.permissions[page], [`can_${action}`]: !current.permissions[page]?.[`can_${action}`] } } }));
  const submit = async (event) => { event.preventDefault(); setBusy(true); try { const data = { username: form.username, roleId: form.role_id || undefined, isActive: form.is_active, isPermission: form.is_permission, allowedPages: Object.entries(form.permissions).filter(([, v]) => v.can_view || v.can_create || v.can_edit || v.can_delete).map(([page]) => page), permissions: form.permissions }; if (form.password) data.password = form.password; if (form.profilePicture) { const fd = new FormData(); Object.entries(data).forEach(([k, v]) => fd.append(k, typeof v === 'object' ? JSON.stringify(v) : v)); fd.append('profilePicture', form.profilePicture); if (modal.mode === 'create') await usersApi.create(fd); else await usersApi.update(modal.user.id, fd); } else if (modal.mode === 'create') await usersApi.create(data); else await usersApi.update(modal.user.id, data); setModal(null); setToast({ type: 'success', message: 'User saved successfully.' }); await load(); } catch (err) { setToast({ type: 'error', message: err.response?.data?.message || err.message || 'Unable to save user.' }); } finally { setBusy(false); } };
  const remove = async (user) => { if (!window.confirm(`Delete ${user.username}?`)) return; try { await usersApi.remove(user.id); setToast({ type: 'success', message: 'User deleted.' }); await load(); } catch (err) { setToast({ type: 'error', message: err.response?.data?.message || 'Delete failed.' }); } };

  return <div className="page"><Toast message={toast?.message} type={toast?.type} onClose={() => setToast(null)} /><PageHeader title="Users" subtitle="One user table for Admin, Supervisor, Karigar, Helper and custom roles." actions={canCreate('users') && <button className="primary-button" onClick={openCreate}>+ Add User</button>} /><div className="toolbar"><input className="search-input" placeholder="Search users or roles…" value={search} onChange={(e) => setSearch(e.target.value)} /><span className="result-count">{filtered.length} users</span></div><div className="table-card"><div className="table-scroll"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Permissions</th><th>Created</th>{(canEdit('users') || canDelete('users')) && <th>Actions</th>}</tr></thead><tbody>{filtered.map((user) => <tr key={user.id}><td><div className="person-cell">{user.profilePicture ? <img className="avatar-img" src={fileUrl(user.profilePicture)} alt="" /> : <div className="avatar">{(user.username || 'U')[0]}</div>}<span>{user.username}</span></div></td><td><span className="badge">{user.role || '—'}</span></td><td><span className={`status-badge ${user.isActive === false ? 'muted' : 'success'}`}>{user.isActive === false ? 'Inactive' : 'Active'}</span></td><td>{user.permissions ? Object.values(user.permissions).reduce((total, value) => total + ['can_view', 'can_create', 'can_edit', 'can_delete'].filter((k) => value?.[k]).length, 0) : 0} actions</td><td>{user.createdAt ? new Date(user.createdAt).toLocaleDateString() : '—'}</td>{(canEdit('users') || canDelete('users')) && <td><div className="row-actions">{canEdit('users') && <button className="text-button" onClick={() => openEdit(user)}>Edit</button>}{canDelete('users') && <button className="danger-link" onClick={() => remove(user)}>Delete</button>}</div></td>}</tr>)}</tbody></table></div></div>
    {modal && <Modal title={modal.mode === 'create' ? 'Create User' : `Edit ${modal.user.username}`} onClose={() => setModal(null)} footer={<><button className="secondary-button" onClick={() => setModal(null)}>Cancel</button><button className="primary-button" form="user-form" disabled={busy}>{busy ? 'Saving…' : 'Save User'}</button></>}><form id="user-form" className="form-grid" onSubmit={submit}><label>Username<input required value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} /></label><label>{modal.mode === 'create' ? 'Password' : 'New Password'}<input type="password" required={modal.mode === 'create'} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label><label>Role<select value={form.role_id} onChange={(e) => setForm({ ...form, role_id: e.target.value })} required><option value="">Select role</option>{roles.map((role) => <option value={role.id} key={role.id}>{role.name}</option>)}</select></label><label>Profile picture<input type="file" accept="image/*" onChange={(e) => setForm({ ...form, profilePicture: e.target.files?.[0] || null })} /></label><label><span className="check-wrap"><input type="checkbox" checked={form.is_active} onChange={(e) => setForm({ ...form, is_active: e.target.checked })} /> Active</span></label><label><span className="check-wrap"><input type="checkbox" checked={form.is_permission} onChange={(e) => setForm({ ...form, is_permission: e.target.checked })} /> Permission system enabled</span></label></form><div className="permission-editor"><div className="permission-header"><div><h3>Page Permissions</h3><p>Admin can grant each action independently.</p></div><div className="permission-bulk">{ACTIONS.map((action) => <button type="button" className="chip-button" key={action} onClick={() => setAll(action, true)}>Select all {action}</button>)}<button type="button" className="chip-button ghost" onClick={() => setForm((current) => ({ ...current, permissions: buildPermissions() }))}>Clear all</button></div></div><div className="permission-table"><div className="permission-row permission-head"><span>Page</span>{ACTIONS.map((action) => <span key={action}>{action}</span>)}</div>{pages.map((page) => <div className="permission-row" key={page.key}><span>{page.label}</span>{ACTIONS.map((action) => <label key={action} className="permission-check"><input type="checkbox" checked={Boolean(form.permissions[page.key]?.[`can_${action}`])} onChange={() => togglePermission(page.key, action)} /><span /></label>)}</div>)}</div></div></Modal>}
  </div>;
}
